stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - cd getstarted  # Navigate to the correct subdirectory
  script:
    - python manage.py test  # Run tests

deploy:
  stage: deploy
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
    - cd getstarted  # Navigate to the correct subdirectory
  script:
    - echo "Deploying Django App..."
    - python manage.py runserver 0.0.0.0:8000 &  # Start server for demo
  only:
    - main
